config/routes.rb
Rails.application.routes.draw do
  scope defaults: { format: 'json' } do
    root 'ember#index'

    get :csrf, to: 'csrf#index'

    devise_for :users, skip: [:registrations], controllers: { sessions: 'sessions' }
    
    resources :organizations, only: [] do
      member do
        get 'dashboard'
      end
    end

    resources :employees, path: ':organization_id/employees', except: [:show]
    resources :projects, path: ':organization_id/projects'
    
    resources :project_assignments do
      collection do
        get 'for_person', path: 'for_person/:person_id'
      end
    end
    
    resources :weekly_project_assignments

    resources :users, only: [:show, :create] do
      collection do
        get 'profile'
      end
    end

    devise_for :users, skip: [:sessions, :registrations]
  end

end

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :hour_capacity
    = f.number_field :hour_capacity
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th Name
    %th Title
    %th Description
    %th Hour capacity
    %th User
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= person.name
      %td= person.title
      %td= person.description
      %td= person.hour_capacity
      %td= person.user
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @person.name
%p
  %b Title:
  = @person.title
%p
  %b Description:
  = @person.description
%p
  %b Hour capacity:
  = @person.hour_capacity
%p
  %b User:
  = @person.user

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path