config/routes.rb
Rails.application.routes.draw do
  scope defaults: { format: 'json' } do
    root 'ember#index'

    get :csrf, to: 'csrf#index'

    devise_for :users, skip: [:registrations], controllers: { sessions: 'sessions' }
    
    resources :organizations, only: [] do
      member do
        get 'dashboard'
      end
    end

    resources :employees, path: ':organization_id/employees', except: [:show]
    resources :projects, path: ':organization_id/projects'
    
    resources :project_assignments do
      collection do
        get 'for_person', path: 'for_person/:person_id'
      end
    end
    
    resources :weekly_project_assignments

    resources :users, only: [:show, :create] do
      collection do
        get 'profile'
      end
    end

    devise_for :users, skip: [:sessions, :registrations]
  end

end

app/models/project_assignment.rb
#== Schema Information
#
# Table name: project_assignments
#
#  id          :integer          not null, primary key
#  employee_id :integer
#  project_id  :integer
#  summary     :string           default("")
#  start_date  :datetime
#  end_date    :datetime
#

class ProjectAssignment < ActiveRecord::Base
  belongs_to :employee
  belongs_to :project

  validates :employee_id, :project_id, :start_date, :end_date, presence: true

  def self.for_organization(organization)
    joins(:project).where(projects: { organization_id: organization.id })
  end

  def organization
    project.organization
  end
end

app/controllers/project_assignments_controller.rb
class ProjectAssignmentsController < ApplicationController
  before_action :authenticate_user_from_token!
  before_action :set_project_assignment, only: [:show, :edit, :update, :destroy]

  # GET /project_assignments.json
  def index
    @project_assignments = ProjectAssignment.for_user(current_user)
    render json: @project_assignments, status: 200
  end

  # GET /project_assignments/1.json
  def show
    render json: @project_assignment
  end

  # GET /project_assignments/for_person/1.json
  def for_person
    render json: ProjectAssignment.where(person_id: params[:person_id]), status: 200
  end

  # POST /project_assignments.json
  def create
    person_id = params[:project_assignment][:person_id]
    person_id ||= params[:project_assignment][:person][:id]
    project_id = params[:project_assignment][:project_id]
    project_id ||= params[:project_assignment][:project][:id]

    person =  Person.where(user: current_user).find(person_id)
    project = Project.where(user: current_user).find(project_id)

    @project_assignment = ProjectAssignment.new(project_assignment_params)
    @project_assignment.person = person
    @project_assignment.project = project

    if @project_assignment.save
      render json: @project_assignment, status: :created
    else
      render json: @project_assignment.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /project_assignments/1.json
  def update
    if @project_assignment.update(project_assignment_params)
      render json: @project_assignment, status: 200
    else
      render json: @project_assignment.errors, status: :unprocessable_entity
    end
  end

  # DELETE /project_assignments/1.json
  def destroy
    @project_assignment.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_assignment
      # join over to projects to make sure the project belongs to the user
      @project_assignment = ProjectAssignment.for_user(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_assignment_params
      params.require(:project_assignment).permit(:summary)
    end
end

app/views/project_assignments/_form.html.slim
= form_for @project_assignment do |f|
  - if @project_assignment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project_assignment.errors.count, "error")} prohibited this project_assignment from being saved:"
      ul
        - @project_assignment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :person
    = f.text_field :person
  .field
    = f.label :project
    = f.text_field :project
  .field
    = f.label :summary
    = f.text_field :summary
  .actions = f.submit 'Save'

app/views/project_assignments/edit.html.slim
h1 Editing project_assignment

== render 'form'

= link_to 'Show', @project_assignment
'|
= link_to 'Back', project_assignments_path

app/views/project_assignments/index.html.slim
h1 Listing project_assignments

table
  thead
    tr
      th Person
      th Project
      th Summary
      th
      th
      th

  tbody
    - @project_assignments.each do |project_assignment|
      tr
        td = project_assignment.person
        td = project_assignment.project
        td = project_assignment.summary
        td = link_to 'Show', project_assignment
        td = link_to 'Edit', edit_project_assignment_path(project_assignment)
        td = link_to 'Destroy', project_assignment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Project assignment', new_project_assignment_path

app/views/project_assignments/new.html.slim
h1 New project_assignment

== render 'form'

= link_to 'Back', project_assignments_path

app/views/project_assignments/show.html.slim
p#notice = notice

p
  strong Person:
  = @project_assignment.person
p
  strong Project:
  = @project_assignment.project
p
  strong Summary:
  = @project_assignment.summary

= link_to 'Edit', edit_project_assignment_path(@project_assignment)
'|
= link_to 'Back', project_assignments_path