config/routes.rb
Rails.application.routes.draw do
  scope defaults: { format: 'json' } do
    root 'ember#index'

    get :csrf, to: 'csrf#index'

    devise_for :users, skip: [:registrations], controllers: { sessions: 'sessions' }
    
    resources :organizations, only: [] do
      member do
        get 'dashboard'
      end
    end

    resources :employees, path: ':organization_id/employees', except: [:show]
    resources :projects, path: ':organization_id/projects'
    
    resources :project_assignments do
      collection do
        get 'for_person', path: 'for_person/:person_id'
      end
    end
    
    resources :weekly_project_assignments

    resources :users, only: [:show, :create] do
      collection do
        get 'profile'
      end
    end

    devise_for :users, skip: [:sessions, :registrations]
  end

end

app/views/weekly_project_assignments/_form.html.slim
= form_for @weekly_project_assignment do |f|
  - if @weekly_project_assignment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@weekly_project_assignment.errors.count, "error")} prohibited this weekly_project_assignment from being saved:"
      ul
        - @weekly_project_assignment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :project_assignment
    = f.text_field :project_assignment
  .field
    = f.label :week_start
    = f.text_field :week_start
  .field
    = f.label :days_working
    = f.number_field :days_working
  .actions = f.submit 'Save'

app/views/weekly_project_assignments/edit.html.slim
h1 Editing weekly_project_assignment

== render 'form'

= link_to 'Show', @weekly_project_assignment
'|
= link_to 'Back', weekly_project_assignments_path

app/views/weekly_project_assignments/index.html.slim
h1 Listing weekly_project_assignments

table
  thead
    tr
      th Project assignment
      th Week start
      th Days working
      th
      th
      th

  tbody
    - @weekly_project_assignments.each do |weekly_project_assignment|
      tr
        td = weekly_project_assignment.project_assignment
        td = weekly_project_assignment.week_start
        td = weekly_project_assignment.days_working
        td = link_to 'Show', weekly_project_assignment
        td = link_to 'Edit', edit_weekly_project_assignment_path(weekly_project_assignment)
        td = link_to 'Destroy', weekly_project_assignment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Weekly project assignment', new_weekly_project_assignment_path

app/views/weekly_project_assignments/new.html.slim
h1 New weekly_project_assignment

== render 'form'

= link_to 'Back', weekly_project_assignments_path

app/views/weekly_project_assignments/show.html.slim
p#notice = notice

p
  strong Project assignment:
  = @weekly_project_assignment.project_assignment
p
  strong Week start:
  = @weekly_project_assignment.week_start
p
  strong Days working:
  = @weekly_project_assignment.days_working

= link_to 'Edit', edit_weekly_project_assignment_path(@weekly_project_assignment)
'|
= link_to 'Back', weekly_project_assignments_path